  ###REGISTER USER
POST http://localhost:5500/users/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admintim@example.com",
    "password": "adminpass123"
}

###LOGIN USER
POST http://localhost:5500/users/login
Content-Type: application/json

{
    "email": "admintim@example.com",
    "password": "adminpass123"
}



###FETCH ALL USERS
GET http://localhost:5500/users/fetch-all-users
Content-Type: application/json


###FETCH USERS(ROLE(USER))
GET http://localhost:5500/users/fetch-users
Content-Type: application/json


### FETCH SINGLE USER
GET http://localhost:5500/users/dc14ba01-77b1-4729-9a46-1cf33213f3a6
Content-Type: application/json


###SWITCH ROLES
PUT http://localhost:5500/users/switch-role
Content-Type: application/json

{
    "user_id":"dc14ba01-77b1-4729-9a46-1cf33213f3a6"
}


###CHANGE USER PASSWORD
PUT http://localhost:5500/users/admin@example.com
Content-Type: application/json

{
    "password": "12345678"
}


###DEACTIVATE USER
PUT http://localhost:5500/users/deactivate/64f849bf-cfef-4f9b-9577-b2f894d8e77c

###ACTIVATE USER
PUT http://localhost:5500/users/activate/64f849bf-cfef-4f9b-9577-b2f894d8e77c


###GET THE NUMBER OF USERS
GET http://localhost:5500/users/user/countUsers
Content-Type: application/json

###GET NUMBER OF USERS IN ROLES
GET http://localhost:5500/users/user/countUserRole
Content-Type: application/json